spring.application.name=restaurant

server.port=8088

spring.datasource.url=jdbc:postgresql://localhost:5432/RestaurantsDatabase
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

app.pagination.default-page=1
app.pagination.default-size=10
app.pagination.max-size=30

app.web.url=/images/
spring.web.resources.static-locations=file:/home/maher/restaurant-uploads/
spring.web.resources.static-path-pattern=/images/**
app.upload.path=/home/maher/restaurant-uploads/

spring.jpa.open-in-view=false

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.leak-detection-threshold=60000
spring.datasource.hikari.auto-commit=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

spring.data.redis.lettuce.pool.min-idle=2
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.max-active=20
spring.data.redis.lettuce.pool.max-wait=2000ms
spring.data.redis.timeout=2000ms

# Create separate API groups
springdoc.group-configs[0].group=categories
springdoc.group-configs[0].paths-to-match=/api/v1/categories/**
springdoc.group-configs[0].packages-to-scan=com.wajba.restaurant.Controller

springdoc.group-configs[1].group=menu-items
springdoc.group-configs[1].paths-to-match=/api/v1/menu-items/**
springdoc.group-configs[1].packages-to-scan=com.wajba.restaurant.Controller

springdoc.group-configs[2].group=modifiers
springdoc.group-configs[2].paths-to-match=/api/v1/modifiers/**
springdoc.group-configs[2].packages-to-scan=com.wajba.restaurant.Controller

# Enable group selector in UI
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true
